@startuml
'https://plantuml.com/class-diagram

class Счёт {
    Название
    Брокер
    Номер у брокера
    Текущий баланс
}

class Операция {
    Дата и время
    Счёт
    Актив
    Тип поерации
    Количество
    Стоимость единицы
}
class АктивНаСчёте {
    Код актива
    Тип актива
    Количество
    Цена покупки
    Текущая цена
}

enum ТипОперации {
Пополнение
}
enum ТипАктива {
Валюта
}

Счёт *-- Операция
Счёт *-- АктивНаСчёте
Операция o-- ТипОперации
АктивНаСчёте o-- ТипАктива

@enduml