:toc:
:toclevels: 3
= Требования

== 1. Общая информация

=== 1.1 Термины

Счёт - это сущность, которая определяется названием, и уникальным сочетанием названия брокера и номера. Данная сущность группирует часть активов.

=== 1.2 Общие принципы построения API

Api разрабатывается на принципах RPC. Т.е. REST методология не применяется. Коды ответов отличные от 200 говорят о проблемах на уровне интеграции либо контракта.

Все запросы используют только метод POST. Тело запроса всегда передаётся в формате JSON.

Каждый запрос, если он попал внутрь логики приложения должен вернуть код 200 и ответ вида:

[source, rest]
----
{
    status: <"SUCCESS"|"WARN"|"ERROR">,
    errorMessage: <Текст ошибки, если логика приложения не может быть выполнена при таких входных параметрах. Для status = "WARN" или "ERROR">,
    responce: <Тело ответа в формате JSON>,
}
----

==== 1.2.1 Валидация входных параметров

Валидация входных параметров является зоной ответственности контроллера, и результат валидации возвращается в вышеуказанном формате с таипом ответа "ERROR".
На пример:

[source, rest]
----
{
    status: "ERROR",
    errorMessage: "Не правильный запрос",
    responce: {
        [
            {
                field: "name"
                message: "Поле не может быть пустым"
            },
            {
                field: "broker"
                message: "Поле не может быть пустым"
            }
        ]
    },
}
----

В ответе указываются только те поля, которые указаны не корректно

=== 1.3 Хранение сущностей

Каждая сущность должна иметь поле id в формате uuid

== 2. Функциональные требования

=== 2.10 Управление счетами

==== 2.10.1 Создание счёта

Система должна позволять создавать счёт

[source, rest]
----
POST /api/v1/create-account

{
    name: <Название>,
    broker: <Название брокера>,
    number: <номер у брокера>
}
----

#Все поля являются обязательными.#

В случае, если если счёт успешно создан, сервер должен вернуть код 200 и ответ
[source, rest]
----
Content-Type: application/json

{
    status: "SUCCESS"
    responce: {
        id: <идентификатор созданного счёта>
    }
}
----

Если в системе зарегистрирован счёт у этого брокера с таким номером - необходимо вернуть предупреждение

[source, rest]
----
{
    status: "WARN",
    errorMessage: "В системе уже зарегистрирован счёт <номер счёта> у брокера <название брокера>"
}
----

==== 2.10.2 обновление счёта

Система должна позволять создавать счёт

[source, rest]
----
POST /api/v1/update-account

{
    id: <идентификатор счёта>,
    name: <Название>,
    broker: <Название брокера>,
    number: <номер у брокера>
}
----

#Все поля являются обязательными.#

В случае, если если счёт успешно обновлён, сервер должен вернуть код 200 и ответ
[source, rest]
----
Content-Type: appliction/json

{
    status: "SUCCESS"
    responce: {
        id: <идентификатор обновлённого счёта>
    }
}
----

Если в системе нет счёта с таким id - необходимо вернуть ответ

[source, rest]
----
{
    status: "WARN",
    errorMessage: "Нет счёта с идентификатором <id>"
}
----

Если в системе зарегистрирован другой счёт у этого брокера с таким номером - необходимо вернуть предупреждение

[source, rest]
----
{
    status: "WARN",
    errorMessage: "В системе уже зарегистрирован счёт <номер счёта> у боркера <название брокера>"
}
----

==== 2.10.3 Удаление счёта

Система должна позволять удалять счёт

[source, rest]
----
POST /api/v1/delete-account

{
    id: <идентификатор счёта>
}
----

#Все поля являются обязательными.#

В случае, если если счёт успешно удалён, сервер должен вернуть код 200 и ответ
[source, rest]
----
Content-Type: appliction/json

{
    status: "SUCCESS"
    responce: {
        id: <идентификатор удалённого счёта>
    }
}
----

Если в системе нет счёта с таким id - необходимо вернуть ответ

[source, rest]
----
{
    status: "WARN",
    errorMessage: "Нет счёта с идентификатором <id>"
}
----

==== 2.10.4 Отображение списка счетов

Система должна позволять создавать список, перечисление счетов

[source, rest]
----
POST /api/v1/get-accounts-list

----

[source, rest]
----
Content-Type: appliction/json

{
    status: "SUCCESS",
    responce: {
        list: [
            {
                id: <идентификатор счёта>,
                name: <Название>,
                broker: <Название брокера>,
                number: <номер у брокера>
            },
            {
                id: <идентификатор счёта>,
                name: <Название>,
                broker: <Название брокера>,
                number: <номер у брокера>
            },
            ...
        ]
    }
}
----

==== 2.10.5 Получение подробной информации о счёте

Система должна возвращать подробную информацию о счёте

[source, rest]
----
POST /api/v1/get-accounts-info

{
    id: <идентификатор счёта>
}
----

В результате успеха необходимо вернуть ответ

[source, rest]
----
Content-Type: appliction/json

{
    status: "SUCCESS",
    responce: {
        id: <идентификатор счёта>,
        name: <Название>,
        broker: <Название брокера>,
        number: <номер у брокера>
    }
}
----

Если счёт не был найден необходимо вернуть ошибку

[source, rest]
----
Content-Type: appliction/json

{
    status: "WARN",
    errorMessage: "Нет счёта с идентификатором <id>"
}
----
