:toc:
:toclevels: 3
= Требования

== 1. Общая информация

=== 1.1 Термины

=== 1.1.1 Описание сущностей
* Актив на счёте - сущность, которая определяет количество , стоимость текущую и стоимость приобретения единицы валюты, акции, или любой другой ценной бумагт

* Операция - сущность отображающая измменение количества активов на счёте

* Счёт - это сущность, которая определяется названием, и уникальным сочетанием названия брокера и номера. Данная сущность группирует часть активов.

==== 1.1.2 Диаграмма классов

[plantuml]
----
include::./diagrams/Entities.puml[]
----

=== 1.2 Общие принципы построения API

Api разрабатывается на принципах RPC. Т.е. REST методология не применяется. Коды ответов отличные от 200 говорят о проблемах на уровне интеграции либо контракта.

Все запросы используют только метод POST. Тело запроса всегда передаётся в формате JSON.

Каждый запрос, если он попал внутрь логики приложения должен вернуть код 200 и ответ вида:

[source, rest]
----
{
    status: <"SUCCESS"|"WARN"|"ERROR">,
    errorMessage: <Текст ошибки, если логика приложения не может быть выполнена при таких входных параметрах. Для status = "WARN" или "ERROR">,
    responce: <Тело ответа в формате JSON>,
}
----

==== 1.2.1 Валидация входных параметров

Валидация входных параметров является зоной ответственности контроллера, и результат валидации возвращается в вышеуказанном формате с таипом ответа "ERROR".
На пример:

[source, rest]
----
{
    status: "ERROR",
    errorMessage: "Не правильный запрос",
    responce: {
        [
            {
                field: "name"
                message: "Поле не может быть пустым"
            },
            {
                field: "broker"
                message: "Поле не может быть пустым"
            }
        ]
    },
}
----

В ответе указываются только те поля, которые указаны не корректно

=== 1.2.2. Типизация ошибок

==== 1.2.2.1 ERROR

Тип ошибки ERROR используется, в том случае, когда запрос с клиента придти не мог. Примеры:

* Пришли данные, которые не удовлетворяют формату:
** Отсутствует обязательное поле
** Обязательное поле принимает не правильный формат
* Пришёл запрос на пополнение не существующего счёта
* Пришёл запрос на удаление не существующего счёта
* Пришёл запрос на продажу не существующего актива

==== 1.2.2.2 WARN

Тип ошибки WARN используется для указания на логическую ошибку или ошибку в синхронизации данных между сервером и клиентом. Примеры:

* Попытка снять сумму со счёта превышающую сумму актива RUR
* Проведение операции, когда один из активов увеличивается на количество превышающее текущее значение

=== 1.2.3 Форматы данных


|===
|Тип данных |формат

|Дата
|"yyyy.MM.dd"

|Дата и время
|"yyyy.MM.dd hh:mm"
|===


=== 1.3 Хранение сущностей

Каждая сущность должна иметь поле id в формате uuid

== 2. Функциональные требования

=== 2.1 Пополнение счёта
Система должна давать возможность внести деньги на счёт. При внесении денег на счёт должно происходить следующее:

. У сущности счёт должно увеличиваться поле текущий баланс
. Должна появляться операция с типом внесение денег на счёт
. Должен создаваться актив на счёте:
.. с типом *валюта*
.. с кодом *RUR*
.. со стоимостью 1.0
.. с указанным количеством
. Если актив с таким кодом есть, то необходимо увеличивать количество на указанное значение

Данная операция должна происходит атомарно.

*Запрос*

[source, rest]
----
POST /api/v1/replenish-account

{
    accountId: uuid
    amount: <сумма>,
}
----

Успешный ответ
[source, json]
----
{
    "status": "SUCCESS",
    "responce": {
        "id": "<идентификатор счёта>"
    }
}
----

=== 2.2 Вывод средств со счета

Система должна давать возможность вывести деньги со счёта. При выводе денег со счёта должно происходить следующее:

. У актива RUR должно уменьшаться количество.
.. Если количество актива RUR меньше запрашиваемой суммы, то операция должна быть отменена
.. Если количество актива после вычитания = 0, то актив надо удалить со счёта
. У сущности счёт должно уменьшаться поле текущий баланс
.. Поле баланс не должно становиться отрицательным
. Должна появляться операция с типом вывода денег со счёта с указанием:
.. валюты  *RUR*
.. количества
.. стоимость единицы актива = 1

Данная операция должна происходит атомарно.

*Запрос*

[source, rest]
----
POST /api/v1/withdraw-from-account

{
    accountId: uuid
    amount: <сумма>,
}
----

Успешный ответ
[source, json]
----
{
    "status": "SUCCESS",
    "responce": {
        "id": "<идентификатор счёта>"
    }
}
----

Ошибочный ответ
[source, json]
----
{
    "status": "ERROR",
    "errorMessage": "На счёте \"<НАЗВАНИЕ_СЧЕТА>\" не достаточно средств"
}
----


=== 2.3 Видеть все активы счёта
Система должна давать возможность видеть все активы указанного счёта.
Список активов?

[source, rest]
----
POST /api/v1/get-purchased-assets-list
----
[source, rest]
----
Content-Type: application/json
{
    status: "SUCCESS",
    response: {
        list: [
            {
                code: <код актива> ,
                assetType: <тип актива>,
                amount: <количество>,
                purchasePrice: <стоимость покупки>,
                currentPrice: <текущая стоимость>
            },
            {
                code: <код актива> ,
                assetType: <тип актива>,
                amount: <количество>,
                purchasePrice: <стоимость покупки>,
                currentPrice: <текущая стоимость>
            },
            ...
        ]
    }
}
----

=== 2.4 Приобретение, добавление активов: руб, валюта, драгМет, акции, облигации

Система должна позволять купить актив. Во время покупки актива должно происходить следующее:

. Создаваться операция "Покупка актива". Параметры операции:
** Идентификатор счета
** Код актива
** Количество купленного актива
** Стоимость одной единицы актива
** дата и время, если не установлены - сейчас. Если пришла только дата, то время операции фиксируется 18-00
. Уменьшаться актив RUR
. Появляться новый актив или увеличиваться его количество.
** Если актива не существует, то цена покупки и текущая цена равны указанной цене
** Если актив уже существует, то текущая цена становится равной цене покупки, а цена покупки пересчитывается по формуле (N0*P0 * N1*P1)/(N0+N1). Где:
*** N0 - количество актива до начала операции
*** P0 - цена покупки до начала операции
*** N1 - количество покупаемого актива
*** P1 -цена за которую происходит покупка сейчас
. Если общая сумма операции превышает количество актива RUR на данном счету, то необходимо вывести ошибку о невозможности провести операцию.

*Запрос*

[source, rest]
----
POST /api/v1/purchase-asset

{
    accountId: uuid,
    assetCode: <код актива>,
    amount: <дроьное, количество приобретаемого актива>,
    price: <дробное, стоимость одной единицы актива>,
    date: <дата или дата_время>,
}
----

Ошибочный ответ
[source, json]
----
{
    "status": "WARN",
    "errorMessage": "На счёте не достаточно средств для приобретения актива"
}
----


=== 2.5 Внесение изменений в стоимость актива

=== 2.6 Продажа актива

Система должна позволять продать актив. Во время продажи актива должно происходить следующее:

. Создаваться операция "Продажа актива". Параметры операции:
** Идентификатор счета
** Код актива
** Количество продаваемого актива
** Стоимость одной единицы актива
** дата и время, если не установлены - сейчас. Если пришла только дата, то время операции фиксируется 18-00
. Увеличивается актив RUR на значение равное стоимость * кол-чо
. Количество актива уменьшается. Если количество актива становится равным 0, то актив удаляется.
. Если общее количество актива превышает общее текущее число данного актива, то необходимо вывести ошибку о невозможности провести операцию.

*Запрос*

[source, rest]
----
POST /api/v1/sell-asset

{
    accountId: uuid,
    assetCode: <код актива>,
    amount: <дроьное, количество продаваемого актива>,
    price: <дробное, стоимость одной единицы актива>,
    date: <дата или дата_время>,
}
----

Ошибочный ответ
[source, json]
----
{
    "status": "WARN",
    "errorMessage": "На счёте не достаточное количество актива <код_актива>"
}
----


=== 2.7 Получение дивидендов

=== 2.8 Расчет суммы портфеля: руб, валюта, драгМет, акции, облигации

=== 2.9  Расчет изменений за месяц

=== 2.10 Управление счетами

==== 2.10.1 Создание счёта

Система должна позволять создавать счёт

[source, rest]
----
POST /api/v1/create-account

{
    name: <Название>,
    broker: <Название брокера>,
    number: <номер у брокера>
}
----

#Все поля являются обязательными.#

В случае, если если счёт успешно создан, сервер должен вернуть код 200 и ответ
[source, rest]
----
Content-Type: application/json

{
    status: "SUCCESS"
    responce: {
        id: <идентификатор созданного счёта>
    }
}
----

Если в системе зарегистрирован счёт у этого брокера с таким номером - необходимо вернуть предупреждение

[source, rest]
----
{
    status: "WARN",
    errorMessage: "В системе уже зарегистрирован счёт <номер счёта> у брокера <название брокера>"
}
----

==== 2.10.2 обновление счёта

Система должна позволять создавать счёт

[source, rest]
----
POST /api/v1/update-account

{
    id: <идентификатор счёта>,
    name: <Название>,
    broker: <Название брокера>,
    number: <номер у брокера>
}
----

#Все поля являются обязательными.#

В случае, если если счёт успешно обновлён, сервер должен вернуть код 200 и ответ
[source, rest]
----
Content-Type: appliction/json

{
    status: "SUCCESS"
    responce: {
        id: <идентификатор обновлённого счёта>
    }
}
----

Если в системе нет счёта с таким id - необходимо вернуть ответ

[source, rest]
----
{
    status: "WARN",
    errorMessage: "Нет счёта с идентификатором <id>"
}
----

Если в системе зарегистрирован другой счёт у этого брокера с таким номером - необходимо вернуть предупреждение

[source, rest]
----
{
    status: "WARN",
    errorMessage: "В системе уже зарегистрирован счёт <номер счёта> у боркера <название брокера>"
}
----

==== 2.10.3 Удаление счёта

Система должна позволять удалять счёт

[source, rest]
----
POST /api/v1/delete-account

{
    id: <идентификатор счёта>
}
----

#Все поля являются обязательными.#

В случае, если если счёт успешно удалён, сервер должен вернуть код 200 и ответ
[source, rest]
----
Content-Type: appliction/json

{
    status: "SUCCESS"
    responce: {
        id: <идентификатор удалённого счёта>
    }
}
----

Если в системе нет счёта с таким id - необходимо вернуть ответ

[source, rest]
----
{
    status: "WARN",
    errorMessage: "Нет счёта с идентификатором <id>"
}
----

==== 2.10.4 Отображение списка счетов

Система должна позволять создавать список, перечисление счетов

[source, rest]
----
POST /api/v1/get-accounts-list

----

[source, rest]
----
Content-Type: application/json

{
    status: "SUCCESS",
    response: {
        list: [
            {
                id: <идентификатор счёта>,
                name: <Название>,
                broker: <Название брокера>,
                number: <номер у брокера>,
                currentBalance: <Текущий баланс>
            },
            {
                id: <идентификатор счёта>,
                name: <Название>,
                broker: <Название брокера>,
                number: <номер у брокера>,
                currentBalance: <Текущий баланс>
            },
            ...
        ]
    }
}
----

==== 2.10.5 Получение подробной информации о счёте

Система должна возвращать подробную информацию о счёте

[source, rest]
----
POST /api/v1/get-accounts-info

{
    id: <идентификатор счёта>
}
----

В результате успеха необходимо вернуть ответ

[source, rest]
----
Content-Type: appliction/json

{
    status: "SUCCESS",
    responce: {
        id: <идентификатор счёта>,
        name: <Название>,
        broker: <Название брокера>,
        number: <номер у брокера>,
        currentBalance: <Текущий баланс>
    }
}
----

Если счёт не был найден необходимо вернуть ошибку

[source, rest]
----
Content-Type: appliction/json

{
    status: "WARN",
    errorMessage: "Нет счёта с идентификатором <id>"
}
----

=== 2.11 Отображение изменения стоимости портфеля за период

=== 2.12 Моя цель*

=== 2.13 Отображение всех операций по счету постранично